## 벡터와 행렬 연산
* 벡터 : 크기와 방향을 가진 양
  * 1차원 배열 또는 리스트로 표현
* 행렬 : 행과 열을 가지는 2차원 형상을 가진 구조
  * 2차원 배열로 표현
  * 3차원부터는 주로 텐서라고 부름

### 텐서(Tensor)

In [1]:
import numpy as np

#### 1.0차원 텐서(스칼라)
* 하나의 실수값으로 이루어진 데이터
* 0D 텐서라고도 함

In [2]:
d=np.array(5)
print(d.ndim)
print(d.shape)

0
()


#### 2.1차원 텐서(벡터)
* 숫자를 배열한 것을 벡터라함
* 1D 텐서라고도 함

In [3]:
d=np.array([1,2,3,4])
print(d.ndim)
print(d.shape)

1
(4,)


#### 3. 2차원 텐서(행렬)
* 행과 열이 존재하는 벡터의 배열
* 2D 텐서라고도 함

In [4]:
d=np.array([[1,2],[3,4],[5,6]])
print(d.ndim)
print(d.shape)

2
(3, 2)


#### 4.3차원 텐서(다차원 배열)
* 3차원 이상의 배열부터 본격적으로 텐서라고 부른다

In [6]:
d=np.array([
    [[1,2,3,4], [5,6,7,8], [9,10,11,12]],
     [[11,12,13,14],[15,16,17,18],[19,20,21,22]]
    ])
print(d.ndim)
print(d.shape)

3
(2, 3, 4)


### 벡터와 행렬의 연산

In [11]:
a=np.array([1,2,3])
b=np.array([1,2,3])
print(a+b)
print(a-b)
print(np.dot(a,b)) #벡터내적

[2 4 6]
[0 0 0]
14


In [12]:
A = np.array([[1, 3],[2, 4]])
B = np.array([[5, 7],[6, 8]])
print(np.matmul(A, B)) #행렬 곱

[[23 31]
 [34 46]]
